deployment:
  tasks:
    - export DEPLOYPATH=/home/lloydcul/birdribs/
    - /bin/rm $DEPLOYPATH/*
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp -R public/* $DEPLOYPATH
    - /bin/cp -R assets/img $DEPLOYPATH
